// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.Data.Contexts;

#nullable disable

namespace TaxCalculator.Data.Migrations
{
    [DbContext(typeof(TaxCalcContext))]
    [Migration("20230510192904_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculator.Domain.Entities.TaxRates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("From")
                        .HasColumnType("bigint");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<long>("To")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28d25c47-02cf-4dd2-98a5-e78f3d4b9eae"),
                            From = 0L,
                            Rate = 10,
                            To = 8350L
                        },
                        new
                        {
                            Id = new Guid("070a5228-2949-4c4a-8f68-16b5a248e6fa"),
                            From = 8351L,
                            Rate = 15,
                            To = 33950L
                        },
                        new
                        {
                            Id = new Guid("cef4622a-f7cd-4b40-9a7f-cd224fb046bb"),
                            From = 33951L,
                            Rate = 25,
                            To = 82250L
                        },
                        new
                        {
                            Id = new Guid("ee02a390-afb0-401d-b8d9-7b8643920b31"),
                            From = 82251L,
                            Rate = 28,
                            To = 171550L
                        },
                        new
                        {
                            Id = new Guid("b48e82ad-7893-427e-b10e-011edccaf36a"),
                            From = 171551L,
                            Rate = 33,
                            To = 372950L
                        },
                        new
                        {
                            Id = new Guid("fc909f36-23fd-4387-90e8-3c8b97ea8c6a"),
                            From = 372951L,
                            Rate = 35,
                            To = 9223372036854775807L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
